trigger:
- develop
- feature/AzureDevOps/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '18.14.1'

stages:
- stage: Build
  displayName: 'Build Adventure Works Angular Web App'

  jobs:
  - job: BuildAdventureWorksAngularWebApp
    displayName: 'Build Adventure Works Angular Web App'

    steps:  
    - script: set
      displayName: 'Print All YAML Build Pipleline Variables'

    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --configuration production
      displayName: 'Angular CLI Install and Build Angular App'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/adventure-works'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '''$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'''
        ArtifactName: 'drop'
        publishLocation: 'FilePath'
        TargetPath: 'Container'
